apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterbuilders.kpack.io
spec:
  conversion:
    strategy: None
  group: kpack.io
  names:
    categories:
    - kpack
    kind: ClusterBuilder
    listKind: ClusterBuilderList
    plural: clusterbuilders
    shortNames:
    - clstbldr
    - clstbldrs
    singular: clusterbuilder
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.latestImage
      name: LatestImage
      type: string
    - jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: string
    name: v1alpha2
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          spec:
            type: object
            properties:
              order:
                type: array
                items:
                  type: object
                  properties:
                    group:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: string
              serviceAccountRef:
                type: object
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
              stack:
                type: object
                properties:
                  kind:
                    type: string
                  name:
                    type: string
              store:
                type: object
                properties:
                  kind:
                    type: string
                  name:
                    type: string
              tag:
                type: string
          status:
            type: object
            properties:
              builderMetadata:
                type: array
                items:
                  type: object
                  properties:
                    homepage:
                      type: string
                    id:
                      type: string
                    version:
                      type: string
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    lastTransitionTime:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
              latestImage:
                type: string
              observedGeneration:
                type: integer
              observedStackGeneration:
                type: integer
              observedStoreGeneration:
                type: integer
              order:
                type: array
                items:
                  type: object
                  properties:
                    group:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: string
                          version:
                            type: string
              os:
                type: string
              stack:
                type: object
                properties:
                  id:
                    type: string
                  runImage:
                    type: string
    served: true
    storage: true