apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterstores.kpack.io
spec:
  conversion:
    strategy: None
  group: kpack.io
  names:
    categories:
    - kpack
    kind: ClusterStore
    listKind: ClusterStoreList
    plural: clusterstores
    singular: clusterstore
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: string
    name: v1alpha2
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          spec:
            type: object
            properties:
              serviceAccountRef:
                type: object
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
              sources:
                type: array
                items:
                  type: object
                  properties:
                    image:
                      type: string
          status:
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    lastTransitionTime:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
              observedGeneration:
                type: integer
              buildpacks:
                type: array
                items:
                  type: object
                  properties:
                    api:
                      type: string
                    buildpackage:
                      type: object
                      properties:
                        homepage:
                          type: string
                        id:
                          type: string
                        version:
                          type: string
                    diffId:
                      type: string
                    digest:
                      type: string
                    homepage:
                      type: string
                    id:
                      type: string
                    size:
                      type: integer
                    stacks:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: string
                    storeImage:
                      type: object
                      properties:
                        image:
                          type: string
                    version:
                      type: string
    served: true
    storage: true
