apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterstacks.kpack.io
spec:
  conversion:
    strategy: None
  group: kpack.io
  names:
    categories:
    - kpack
    kind: ClusterStack
    listKind: ClusterStackList
    plural: clusterstacks
    singular: clusterstack
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: string
    name: v1alpha2
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          spec:
            type: object
            properties:
              buildImage:
                type: object
                properties:
                  image:
                    type: string
              id:
                type: string
              runImage:
                type: object
                properties:
                  image:
                    type: string
              serviceAccountRef:
                type: object
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
          status:
            type: object
            properties:
              buildImage:
                type: object
                properties:
                  image:
                    type: string
                  latestImage:
                    type: string
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    lastTransitionTime:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
              groupId:
                type: integer
              id:
                type: string
              mixins:
                type: array
                items:
                  type: string
              observedGeneration:
                type: integer
              runImage:
                type: object
                properties:
                  image:
                    type: string
                  latestImage:
                    type: string
              userId:
                type: integer
    served: true
    storage: true
