apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: customstacks.stacks.stacks-operator.tanzu.vmware.com
spec:
  conversion:
    strategy: None
  group: stacks.stacks-operator.tanzu.vmware.com
  names:
    kind: CustomStack
    listKind: CustomStackList
    plural: customstacks
    singular: customstack
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              caCerts:
                properties:
                  buildRef:
                    properties:
                      name:
                        type: string
                    type: object
                  runRef:
                    properties:
                      name:
                        type: string
                    type: object
                type: object
              destination:
                properties:
                  build:
                    properties:
                      tag:
                        type: string
                    required:
                    - tag
                    type: object
                  run:
                    properties:
                      tag:
                        type: string
                    required:
                    - tag
                    type: object
                  stack:
                    properties:
                      apiVersion:
                        type: string
                      fieldPath:
                        type: string
                      kind:
                        type: string
                      name:
                        type: string
                      namespace:
                        type: string
                      resourceVersion:
                        type: string
                      uid:
                        type: string
                    type: object
                required:
                - build
                - run
                type: object
              mixins:
                items:
                  properties:
                    name:
                      type: string
                    phase:
                      type: string
                  required:
                  - name
                  type: object
                type: array
              packages:
                items:
                  properties:
                    name:
                      type: string
                    phase:
                      type: string
                  required:
                  - name
                  type: object
                type: array
              serviceAccountName:
                type: string
              source:
                properties:
                  registryImages:
                    properties:
                      build:
                        properties:
                          image:
                            pattern: .*@sha256:[A-Fa-f0-9]{64}
                            type: string
                        required:
                        - image
                        type: object
                      run:
                        properties:
                          image:
                            pattern: .*@sha256:[A-Fa-f0-9]{64}
                            type: string
                        required:
                        - image
                        type: object
                    required:
                    - build
                    - run
                    type: object
                  stack:
                    properties:
                      apiVersion:
                        description: API version of the referent.
                        type: string
                      fieldPath:
                        type: string
                      kind:
                        type: string
                      name:
                        type: string
                      namespace:
                        type: string
                      resourceVersion:
                        type: string
                      uid:
                        type: string
                    type: object
                type: object
              user:
                properties:
                  groupID:
                    type: integer
                  userID:
                    type: integer
                required:
                - userID
                type: object
            required:
            - destination
            - source
            type: object
          status:
            properties:
              baseBuildImage:
                type: string
              baseRunImage:
                type: string
              buildImage:
                type: string
              conditions:
                items:
                  properties:
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              id:
                type: string
              lastBuildTime:
                format: date-time
                type: string
              runImage:
                type: string
            type: object
        type: object
    served: true
    storage: true
