apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: images.kpack.io
spec:
  group: kpack.io
  versions:
  - name: v1alpha2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          spec:
            type: object
            properties:
              build:
                type: object
                properties:
                  env:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        value:
                          type: string
                  resources:
                    type: object
                    properties: { }
                  services:
                    type: array
                    items:
                      type: object
                      properties:
                        kind:
                          type: string
                        name:
                          type: string
              builder:
                type: object
                properties:
                  kind:
                    type: string
                  name:
                    type: string
              cache:
                type: object
                properties:
                  volume:
                    type: object
                    properties:
                      size:
                        type: string
              failedBuildHistoryLimit:
                type: integer
              imageTaggingStrategy:
                type: string
              serviceAccountName:
                type: string
              source:
                type: object
                properties:
                  git:
                    type: object
                    properties:
                      url:
                        type: string
                      revision:
                        type: string
                  blob:
                    type: object
                    properties:
                      url:
                        type: string
                      stripComponents:
                        type: number
                  registry:
                    type: object
                    properties:
                      image:
                        type: string
                      imagePullSecrets:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                  subPath:
                    type: string
              successBuildHistoryLimit:
                type: integer
              tag:
                type: string
              additionalTags:
                type: array
                items:
                  type: string
          status:
            type: object
            properties:
              buildCacheName:
                type: string
              buildCounter:
                type: integer
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    lastTransitionTime:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
              latestBuildImageGeneration:
                type: integer
              latestBuildReason:
                type: string
              latestBuildRef:
                type: string
              latestImage:
                type: string
              latestStack:
                type: string
              observedGeneration:
                type: integer
    subresources:
      status: { }
    additionalPrinterColumns:
    - name: LatestImage
      type: string
      jsonPath: ".status.latestImage"
    - name: Ready
      type: string
      jsonPath: ".status.conditions[?(@.type==\"Ready\")].status"
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: kpack-webhook
          namespace: kpack
          path: /convert
          port: 443
      conversionReviewVersions: [ "v1" ]
  names:
    kind: Image
    listKind: ImageList
    singular: image
    plural: images
    shortNames:
    - cnbimage
    - cnbimages
    - img
    - imgs
    categories:
    - kpack
  scope: Namespaced