apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sourceresolvers.kpack.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: kpack-webhook
          namespace: kpack
          path: /convert
          port: 443
      conversionReviewVersions:
      - v1
  group: kpack.io
  names:
    categories:
    - kpack
    kind: SourceResolver
    listKind: SourceResolverList
    plural: sourceresolvers
    singular: sourceresolver
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: string
    name: v1alpha2
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          spec:
            type: object
            properties:
              serviceAccount:
                type: string
              source:
                type: object
                properties:
                  git:
                    type: object
                    properties:
                      url:
                        type: string
                      revision:
                        type: string
                  blob:
                    type: object
                    properties:
                      url:
                        type: string
                      stripComponents:
                        type: number
                  registry:
                    type: object
                    properties:
                      image:
                        type: string
                      imagePullSecrets:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                  subPath:
                    type: string
          status:
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    lastTransitionTime:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
              observedGeneration:
                type: integer
              source:
                type: object
                properties:
                  git:
                    type: object
                    properties:
                      url:
                        type: string
                      revision:
                        type: string
                  blob:
                    type: object
                    properties:
                      url:
                        type: string
                      stripComponents:
                        type: number
                  registry:
                    type: object
                    properties:
                      image:
                        type: string
                      imagePullSecrets:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                  subPath:
                    type: string
    served: true
    storage: true
