/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.kpack.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kpack.models.V1alpha2BuilderSpecOrder;
import io.kpack.models.V1alpha2BuilderSpecStack;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1alpha2BuilderSpec
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
		date = "2023-03-27T10:54:11.377Z[Etc/UTC]")
public class V1alpha2BuilderSpec {

	public static final String SERIALIZED_NAME_ORDER = "order";

	@SerializedName(SERIALIZED_NAME_ORDER)
	private List<V1alpha2BuilderSpecOrder> order = null;

	public static final String SERIALIZED_NAME_SERVICE_ACCOUNT_NAME = "serviceAccountName";

	@SerializedName(SERIALIZED_NAME_SERVICE_ACCOUNT_NAME)
	private String serviceAccountName;

	public static final String SERIALIZED_NAME_STACK = "stack";

	@SerializedName(SERIALIZED_NAME_STACK)
	private V1alpha2BuilderSpecStack stack;

	public static final String SERIALIZED_NAME_STORE = "store";

	@SerializedName(SERIALIZED_NAME_STORE)
	private V1alpha2BuilderSpecStack store;

	public static final String SERIALIZED_NAME_TAG = "tag";

	@SerializedName(SERIALIZED_NAME_TAG)
	private String tag;

	public V1alpha2BuilderSpec order(List<V1alpha2BuilderSpecOrder> order) {

		this.order = order;
		return this;
	}

	public V1alpha2BuilderSpec addOrderItem(V1alpha2BuilderSpecOrder orderItem) {
		if (this.order == null) {
			this.order = new ArrayList<>();
		}
		this.order.add(orderItem);
		return this;
	}

	/**
	 * Get order
	 * @return order
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public List<V1alpha2BuilderSpecOrder> getOrder() {
		return order;
	}

	public void setOrder(List<V1alpha2BuilderSpecOrder> order) {
		this.order = order;
	}

	public V1alpha2BuilderSpec serviceAccountName(String serviceAccountName) {

		this.serviceAccountName = serviceAccountName;
		return this;
	}

	/**
	 * Get serviceAccountName
	 * @return serviceAccountName
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getServiceAccountName() {
		return serviceAccountName;
	}

	public void setServiceAccountName(String serviceAccountName) {
		this.serviceAccountName = serviceAccountName;
	}

	public V1alpha2BuilderSpec stack(V1alpha2BuilderSpecStack stack) {

		this.stack = stack;
		return this;
	}

	/**
	 * Get stack
	 * @return stack
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public V1alpha2BuilderSpecStack getStack() {
		return stack;
	}

	public void setStack(V1alpha2BuilderSpecStack stack) {
		this.stack = stack;
	}

	public V1alpha2BuilderSpec store(V1alpha2BuilderSpecStack store) {

		this.store = store;
		return this;
	}

	/**
	 * Get store
	 * @return store
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public V1alpha2BuilderSpecStack getStore() {
		return store;
	}

	public void setStore(V1alpha2BuilderSpecStack store) {
		this.store = store;
	}

	public V1alpha2BuilderSpec tag(String tag) {

		this.tag = tag;
		return this;
	}

	/**
	 * Get tag
	 * @return tag
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getTag() {
		return tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		V1alpha2BuilderSpec v1alpha2BuilderSpec = (V1alpha2BuilderSpec) o;
		return Objects.equals(this.order, v1alpha2BuilderSpec.order)
				&& Objects.equals(this.serviceAccountName, v1alpha2BuilderSpec.serviceAccountName)
				&& Objects.equals(this.stack, v1alpha2BuilderSpec.stack)
				&& Objects.equals(this.store, v1alpha2BuilderSpec.store)
				&& Objects.equals(this.tag, v1alpha2BuilderSpec.tag);
	}

	@Override
	public int hashCode() {
		return Objects.hash(order, serviceAccountName, stack, store, tag);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class V1alpha2BuilderSpec {\n");
		sb.append("    order: ").append(toIndentedString(order)).append("\n");
		sb.append("    serviceAccountName: ").append(toIndentedString(serviceAccountName)).append("\n");
		sb.append("    stack: ").append(toIndentedString(stack)).append("\n");
		sb.append("    store: ").append(toIndentedString(store)).append("\n");
		sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
