/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.kpack.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kpack.models.V1alpha2ClusterBuilderSpecOrder;
import io.kpack.models.V1alpha2ClusterBuilderSpecServiceAccountRef;
import io.kpack.models.V1alpha2ClusterBuilderSpecStack;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1alpha2ClusterBuilderSpec
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
		date = "2023-03-27T06:34:57.887Z[Etc/UTC]")
public class V1alpha2ClusterBuilderSpec {

	public static final String SERIALIZED_NAME_ORDER = "order";

	@SerializedName(SERIALIZED_NAME_ORDER)
	private List<V1alpha2ClusterBuilderSpecOrder> order = null;

	public static final String SERIALIZED_NAME_SERVICE_ACCOUNT_REF = "serviceAccountRef";

	@SerializedName(SERIALIZED_NAME_SERVICE_ACCOUNT_REF)
	private V1alpha2ClusterBuilderSpecServiceAccountRef serviceAccountRef;

	public static final String SERIALIZED_NAME_STACK = "stack";

	@SerializedName(SERIALIZED_NAME_STACK)
	private V1alpha2ClusterBuilderSpecStack stack;

	public static final String SERIALIZED_NAME_STORE = "store";

	@SerializedName(SERIALIZED_NAME_STORE)
	private V1alpha2ClusterBuilderSpecStack store;

	public static final String SERIALIZED_NAME_TAG = "tag";

	@SerializedName(SERIALIZED_NAME_TAG)
	private String tag;

	public V1alpha2ClusterBuilderSpec order(List<V1alpha2ClusterBuilderSpecOrder> order) {

		this.order = order;
		return this;
	}

	public V1alpha2ClusterBuilderSpec addOrderItem(V1alpha2ClusterBuilderSpecOrder orderItem) {
		if (this.order == null) {
			this.order = new ArrayList<>();
		}
		this.order.add(orderItem);
		return this;
	}

	/**
	 * Get order
	 * @return order
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public List<V1alpha2ClusterBuilderSpecOrder> getOrder() {
		return order;
	}

	public void setOrder(List<V1alpha2ClusterBuilderSpecOrder> order) {
		this.order = order;
	}

	public V1alpha2ClusterBuilderSpec serviceAccountRef(V1alpha2ClusterBuilderSpecServiceAccountRef serviceAccountRef) {

		this.serviceAccountRef = serviceAccountRef;
		return this;
	}

	/**
	 * Get serviceAccountRef
	 * @return serviceAccountRef
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public V1alpha2ClusterBuilderSpecServiceAccountRef getServiceAccountRef() {
		return serviceAccountRef;
	}

	public void setServiceAccountRef(V1alpha2ClusterBuilderSpecServiceAccountRef serviceAccountRef) {
		this.serviceAccountRef = serviceAccountRef;
	}

	public V1alpha2ClusterBuilderSpec stack(V1alpha2ClusterBuilderSpecStack stack) {

		this.stack = stack;
		return this;
	}

	/**
	 * Get stack
	 * @return stack
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public V1alpha2ClusterBuilderSpecStack getStack() {
		return stack;
	}

	public void setStack(V1alpha2ClusterBuilderSpecStack stack) {
		this.stack = stack;
	}

	public V1alpha2ClusterBuilderSpec store(V1alpha2ClusterBuilderSpecStack store) {

		this.store = store;
		return this;
	}

	/**
	 * Get store
	 * @return store
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public V1alpha2ClusterBuilderSpecStack getStore() {
		return store;
	}

	public void setStore(V1alpha2ClusterBuilderSpecStack store) {
		this.store = store;
	}

	public V1alpha2ClusterBuilderSpec tag(String tag) {

		this.tag = tag;
		return this;
	}

	/**
	 * Get tag
	 * @return tag
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getTag() {
		return tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		V1alpha2ClusterBuilderSpec v1alpha2ClusterBuilderSpec = (V1alpha2ClusterBuilderSpec) o;
		return Objects.equals(this.order, v1alpha2ClusterBuilderSpec.order)
				&& Objects.equals(this.serviceAccountRef, v1alpha2ClusterBuilderSpec.serviceAccountRef)
				&& Objects.equals(this.stack, v1alpha2ClusterBuilderSpec.stack)
				&& Objects.equals(this.store, v1alpha2ClusterBuilderSpec.store)
				&& Objects.equals(this.tag, v1alpha2ClusterBuilderSpec.tag);
	}

	@Override
	public int hashCode() {
		return Objects.hash(order, serviceAccountRef, stack, store, tag);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class V1alpha2ClusterBuilderSpec {\n");
		sb.append("    order: ").append(toIndentedString(order)).append("\n");
		sb.append("    serviceAccountRef: ").append(toIndentedString(serviceAccountRef)).append("\n");
		sb.append("    stack: ").append(toIndentedString(stack)).append("\n");
		sb.append("    store: ").append(toIndentedString(store)).append("\n");
		sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
