/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.kpack.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kpack.models.V1alpha2ClusterStoreSpecServiceAccountRef;
import io.kpack.models.V1alpha2ClusterStoreSpecSources;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1alpha2ClusterStoreSpec
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
		date = "2023-03-27T10:29:18.594Z[Etc/UTC]")
public class V1alpha2ClusterStoreSpec {

	public static final String SERIALIZED_NAME_SERVICE_ACCOUNT_REF = "serviceAccountRef";

	@SerializedName(SERIALIZED_NAME_SERVICE_ACCOUNT_REF)
	private V1alpha2ClusterStoreSpecServiceAccountRef serviceAccountRef;

	public static final String SERIALIZED_NAME_SOURCES = "sources";

	@SerializedName(SERIALIZED_NAME_SOURCES)
	private List<V1alpha2ClusterStoreSpecSources> sources = null;

	public V1alpha2ClusterStoreSpec serviceAccountRef(V1alpha2ClusterStoreSpecServiceAccountRef serviceAccountRef) {

		this.serviceAccountRef = serviceAccountRef;
		return this;
	}

	/**
	 * Get serviceAccountRef
	 * @return serviceAccountRef
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public V1alpha2ClusterStoreSpecServiceAccountRef getServiceAccountRef() {
		return serviceAccountRef;
	}

	public void setServiceAccountRef(V1alpha2ClusterStoreSpecServiceAccountRef serviceAccountRef) {
		this.serviceAccountRef = serviceAccountRef;
	}

	public V1alpha2ClusterStoreSpec sources(List<V1alpha2ClusterStoreSpecSources> sources) {

		this.sources = sources;
		return this;
	}

	public V1alpha2ClusterStoreSpec addSourcesItem(V1alpha2ClusterStoreSpecSources sourcesItem) {
		if (this.sources == null) {
			this.sources = new ArrayList<>();
		}
		this.sources.add(sourcesItem);
		return this;
	}

	/**
	 * Get sources
	 * @return sources
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public List<V1alpha2ClusterStoreSpecSources> getSources() {
		return sources;
	}

	public void setSources(List<V1alpha2ClusterStoreSpecSources> sources) {
		this.sources = sources;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		V1alpha2ClusterStoreSpec v1alpha2ClusterStoreSpec = (V1alpha2ClusterStoreSpec) o;
		return Objects.equals(this.serviceAccountRef, v1alpha2ClusterStoreSpec.serviceAccountRef)
				&& Objects.equals(this.sources, v1alpha2ClusterStoreSpec.sources);
	}

	@Override
	public int hashCode() {
		return Objects.hash(serviceAccountRef, sources);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class V1alpha2ClusterStoreSpec {\n");
		sb.append("    serviceAccountRef: ").append(toIndentedString(serviceAccountRef)).append("\n");
		sb.append("    sources: ").append(toIndentedString(sources)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
