/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.kpack.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kpack.models.V1alpha2ClusterStackSpecBuildImage;
import io.kpack.models.V1alpha2ClusterStackSpecServiceAccountRef;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1alpha2ClusterStackSpec
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
		date = "2023-03-27T10:41:15.597Z[Etc/UTC]")
public class V1alpha2ClusterStackSpec {

	public static final String SERIALIZED_NAME_BUILD_IMAGE = "buildImage";

	@SerializedName(SERIALIZED_NAME_BUILD_IMAGE)
	private V1alpha2ClusterStackSpecBuildImage buildImage;

	public static final String SERIALIZED_NAME_ID = "id";

	@SerializedName(SERIALIZED_NAME_ID)
	private String id;

	public static final String SERIALIZED_NAME_RUN_IMAGE = "runImage";

	@SerializedName(SERIALIZED_NAME_RUN_IMAGE)
	private V1alpha2ClusterStackSpecBuildImage runImage;

	public static final String SERIALIZED_NAME_SERVICE_ACCOUNT_REF = "serviceAccountRef";

	@SerializedName(SERIALIZED_NAME_SERVICE_ACCOUNT_REF)
	private V1alpha2ClusterStackSpecServiceAccountRef serviceAccountRef;

	public V1alpha2ClusterStackSpec buildImage(V1alpha2ClusterStackSpecBuildImage buildImage) {

		this.buildImage = buildImage;
		return this;
	}

	/**
	 * Get buildImage
	 * @return buildImage
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public V1alpha2ClusterStackSpecBuildImage getBuildImage() {
		return buildImage;
	}

	public void setBuildImage(V1alpha2ClusterStackSpecBuildImage buildImage) {
		this.buildImage = buildImage;
	}

	public V1alpha2ClusterStackSpec id(String id) {

		this.id = id;
		return this;
	}

	/**
	 * Get id
	 * @return id
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public V1alpha2ClusterStackSpec runImage(V1alpha2ClusterStackSpecBuildImage runImage) {

		this.runImage = runImage;
		return this;
	}

	/**
	 * Get runImage
	 * @return runImage
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public V1alpha2ClusterStackSpecBuildImage getRunImage() {
		return runImage;
	}

	public void setRunImage(V1alpha2ClusterStackSpecBuildImage runImage) {
		this.runImage = runImage;
	}

	public V1alpha2ClusterStackSpec serviceAccountRef(V1alpha2ClusterStackSpecServiceAccountRef serviceAccountRef) {

		this.serviceAccountRef = serviceAccountRef;
		return this;
	}

	/**
	 * Get serviceAccountRef
	 * @return serviceAccountRef
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public V1alpha2ClusterStackSpecServiceAccountRef getServiceAccountRef() {
		return serviceAccountRef;
	}

	public void setServiceAccountRef(V1alpha2ClusterStackSpecServiceAccountRef serviceAccountRef) {
		this.serviceAccountRef = serviceAccountRef;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		V1alpha2ClusterStackSpec v1alpha2ClusterStackSpec = (V1alpha2ClusterStackSpec) o;
		return Objects.equals(this.buildImage, v1alpha2ClusterStackSpec.buildImage)
				&& Objects.equals(this.id, v1alpha2ClusterStackSpec.id)
				&& Objects.equals(this.runImage, v1alpha2ClusterStackSpec.runImage)
				&& Objects.equals(this.serviceAccountRef, v1alpha2ClusterStackSpec.serviceAccountRef);
	}

	@Override
	public int hashCode() {
		return Objects.hash(buildImage, id, runImage, serviceAccountRef);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class V1alpha2ClusterStackSpec {\n");
		sb.append("    buildImage: ").append(toIndentedString(buildImage)).append("\n");
		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    runImage: ").append(toIndentedString(runImage)).append("\n");
		sb.append("    serviceAccountRef: ").append(toIndentedString(serviceAccountRef)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
