/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.kpack.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kpack.models.V1alpha2ClusterStoreStatusBuildpacks;
import io.kpack.models.V1alpha2ClusterStoreStatusConditions;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1alpha2ClusterStoreStatus
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
		date = "2023-03-27T10:29:18.594Z[Etc/UTC]")
public class V1alpha2ClusterStoreStatus {

	public static final String SERIALIZED_NAME_BUILDPACKS = "buildpacks";

	@SerializedName(SERIALIZED_NAME_BUILDPACKS)
	private List<V1alpha2ClusterStoreStatusBuildpacks> buildpacks = null;

	public static final String SERIALIZED_NAME_CONDITIONS = "conditions";

	@SerializedName(SERIALIZED_NAME_CONDITIONS)
	private List<V1alpha2ClusterStoreStatusConditions> conditions = null;

	public static final String SERIALIZED_NAME_OBSERVED_GENERATION = "observedGeneration";

	@SerializedName(SERIALIZED_NAME_OBSERVED_GENERATION)
	private Integer observedGeneration;

	public V1alpha2ClusterStoreStatus buildpacks(List<V1alpha2ClusterStoreStatusBuildpacks> buildpacks) {

		this.buildpacks = buildpacks;
		return this;
	}

	public V1alpha2ClusterStoreStatus addBuildpacksItem(V1alpha2ClusterStoreStatusBuildpacks buildpacksItem) {
		if (this.buildpacks == null) {
			this.buildpacks = new ArrayList<>();
		}
		this.buildpacks.add(buildpacksItem);
		return this;
	}

	/**
	 * Get buildpacks
	 * @return buildpacks
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public List<V1alpha2ClusterStoreStatusBuildpacks> getBuildpacks() {
		return buildpacks;
	}

	public void setBuildpacks(List<V1alpha2ClusterStoreStatusBuildpacks> buildpacks) {
		this.buildpacks = buildpacks;
	}

	public V1alpha2ClusterStoreStatus conditions(List<V1alpha2ClusterStoreStatusConditions> conditions) {

		this.conditions = conditions;
		return this;
	}

	public V1alpha2ClusterStoreStatus addConditionsItem(V1alpha2ClusterStoreStatusConditions conditionsItem) {
		if (this.conditions == null) {
			this.conditions = new ArrayList<>();
		}
		this.conditions.add(conditionsItem);
		return this;
	}

	/**
	 * Get conditions
	 * @return conditions
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public List<V1alpha2ClusterStoreStatusConditions> getConditions() {
		return conditions;
	}

	public void setConditions(List<V1alpha2ClusterStoreStatusConditions> conditions) {
		this.conditions = conditions;
	}

	public V1alpha2ClusterStoreStatus observedGeneration(Integer observedGeneration) {

		this.observedGeneration = observedGeneration;
		return this;
	}

	/**
	 * Get observedGeneration
	 * @return observedGeneration
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public Integer getObservedGeneration() {
		return observedGeneration;
	}

	public void setObservedGeneration(Integer observedGeneration) {
		this.observedGeneration = observedGeneration;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		V1alpha2ClusterStoreStatus v1alpha2ClusterStoreStatus = (V1alpha2ClusterStoreStatus) o;
		return Objects.equals(this.buildpacks, v1alpha2ClusterStoreStatus.buildpacks)
				&& Objects.equals(this.conditions, v1alpha2ClusterStoreStatus.conditions)
				&& Objects.equals(this.observedGeneration, v1alpha2ClusterStoreStatus.observedGeneration);
	}

	@Override
	public int hashCode() {
		return Objects.hash(buildpacks, conditions, observedGeneration);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class V1alpha2ClusterStoreStatus {\n");
		sb.append("    buildpacks: ").append(toIndentedString(buildpacks)).append("\n");
		sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
		sb.append("    observedGeneration: ").append(toIndentedString(observedGeneration)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
