/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.kpack.models;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * V1alpha2ImageSpecSourceRegistry
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
		date = "2023-03-26T09:34:39.833Z[Etc/UTC]")
public class V1alpha2ImageSpecSourceRegistry {

	public static final String SERIALIZED_NAME_IMAGE = "image";

	@SerializedName(SERIALIZED_NAME_IMAGE)
	private String image;

	public static final String SERIALIZED_NAME_IMAGE_PULL_SECRETS = "imagePullSecrets";

	@SerializedName(SERIALIZED_NAME_IMAGE_PULL_SECRETS)
	private List<V1alpha2ImageSpecSourceRegistryImagePullSecrets> imagePullSecrets = null;

	public V1alpha2ImageSpecSourceRegistry image(String image) {

		this.image = image;
		return this;
	}

	/**
	 * Get image
	 * @return image
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getImage() {
		return image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public V1alpha2ImageSpecSourceRegistry imagePullSecrets(
			List<V1alpha2ImageSpecSourceRegistryImagePullSecrets> imagePullSecrets) {

		this.imagePullSecrets = imagePullSecrets;
		return this;
	}

	public V1alpha2ImageSpecSourceRegistry addImagePullSecretsItem(
			V1alpha2ImageSpecSourceRegistryImagePullSecrets imagePullSecretsItem) {
		if (this.imagePullSecrets == null) {
			this.imagePullSecrets = new ArrayList<>();
		}
		this.imagePullSecrets.add(imagePullSecretsItem);
		return this;
	}

	/**
	 * Get imagePullSecrets
	 * @return imagePullSecrets
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public List<V1alpha2ImageSpecSourceRegistryImagePullSecrets> getImagePullSecrets() {
		return imagePullSecrets;
	}

	public void setImagePullSecrets(List<V1alpha2ImageSpecSourceRegistryImagePullSecrets> imagePullSecrets) {
		this.imagePullSecrets = imagePullSecrets;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		V1alpha2ImageSpecSourceRegistry v1alpha2ImageSpecSourceRegistry = (V1alpha2ImageSpecSourceRegistry) o;
		return Objects.equals(this.image, v1alpha2ImageSpecSourceRegistry.image)
				&& Objects.equals(this.imagePullSecrets, v1alpha2ImageSpecSourceRegistry.imagePullSecrets);
	}

	@Override
	public int hashCode() {
		return Objects.hash(image, imagePullSecrets);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class V1alpha2ImageSpecSourceRegistry {\n");
		sb.append("    image: ").append(toIndentedString(image)).append("\n");
		sb.append("    imagePullSecrets: ").append(toIndentedString(imagePullSecrets)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
