/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.kpack.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1alpha2ClusterStoreSpecSources
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
		date = "2023-03-27T10:29:18.594Z[Etc/UTC]")
public class V1alpha2ClusterStoreSpecSources {

	public static final String SERIALIZED_NAME_IMAGE = "image";

	@SerializedName(SERIALIZED_NAME_IMAGE)
	private String image;

	public V1alpha2ClusterStoreSpecSources image(String image) {

		this.image = image;
		return this;
	}

	/**
	 * Get image
	 * @return image
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getImage() {
		return image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		V1alpha2ClusterStoreSpecSources v1alpha2ClusterStoreSpecSources = (V1alpha2ClusterStoreSpecSources) o;
		return Objects.equals(this.image, v1alpha2ClusterStoreSpecSources.image);
	}

	@Override
	public int hashCode() {
		return Objects.hash(image);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class V1alpha2ClusterStoreSpecSources {\n");
		sb.append("    image: ").append(toIndentedString(image)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
