/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.kpack.models;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * V1alpha2ImageStatus
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
		date = "2023-03-26T09:34:39.833Z[Etc/UTC]")
public class V1alpha2ImageStatus {

	public static final String SERIALIZED_NAME_BUILD_CACHE_NAME = "buildCacheName";

	@SerializedName(SERIALIZED_NAME_BUILD_CACHE_NAME)
	private String buildCacheName;

	public static final String SERIALIZED_NAME_BUILD_COUNTER = "buildCounter";

	@SerializedName(SERIALIZED_NAME_BUILD_COUNTER)
	private Integer buildCounter;

	public static final String SERIALIZED_NAME_CONDITIONS = "conditions";

	@SerializedName(SERIALIZED_NAME_CONDITIONS)
	private List<V1alpha2ImageStatusConditions> conditions = null;

	public static final String SERIALIZED_NAME_LATEST_BUILD_IMAGE_GENERATION = "latestBuildImageGeneration";

	@SerializedName(SERIALIZED_NAME_LATEST_BUILD_IMAGE_GENERATION)
	private Integer latestBuildImageGeneration;

	public static final String SERIALIZED_NAME_LATEST_BUILD_REASON = "latestBuildReason";

	@SerializedName(SERIALIZED_NAME_LATEST_BUILD_REASON)
	private String latestBuildReason;

	public static final String SERIALIZED_NAME_LATEST_BUILD_REF = "latestBuildRef";

	@SerializedName(SERIALIZED_NAME_LATEST_BUILD_REF)
	private String latestBuildRef;

	public static final String SERIALIZED_NAME_LATEST_IMAGE = "latestImage";

	@SerializedName(SERIALIZED_NAME_LATEST_IMAGE)
	private String latestImage;

	public static final String SERIALIZED_NAME_LATEST_STACK = "latestStack";

	@SerializedName(SERIALIZED_NAME_LATEST_STACK)
	private String latestStack;

	public static final String SERIALIZED_NAME_OBSERVED_GENERATION = "observedGeneration";

	@SerializedName(SERIALIZED_NAME_OBSERVED_GENERATION)
	private Integer observedGeneration;

	public V1alpha2ImageStatus buildCacheName(String buildCacheName) {

		this.buildCacheName = buildCacheName;
		return this;
	}

	/**
	 * Get buildCacheName
	 * @return buildCacheName
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getBuildCacheName() {
		return buildCacheName;
	}

	public void setBuildCacheName(String buildCacheName) {
		this.buildCacheName = buildCacheName;
	}

	public V1alpha2ImageStatus buildCounter(Integer buildCounter) {

		this.buildCounter = buildCounter;
		return this;
	}

	/**
	 * Get buildCounter
	 * @return buildCounter
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public Integer getBuildCounter() {
		return buildCounter;
	}

	public void setBuildCounter(Integer buildCounter) {
		this.buildCounter = buildCounter;
	}

	public V1alpha2ImageStatus conditions(List<V1alpha2ImageStatusConditions> conditions) {

		this.conditions = conditions;
		return this;
	}

	public V1alpha2ImageStatus addConditionsItem(V1alpha2ImageStatusConditions conditionsItem) {
		if (this.conditions == null) {
			this.conditions = new ArrayList<>();
		}
		this.conditions.add(conditionsItem);
		return this;
	}

	/**
	 * Get conditions
	 * @return conditions
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public List<V1alpha2ImageStatusConditions> getConditions() {
		return conditions;
	}

	public void setConditions(List<V1alpha2ImageStatusConditions> conditions) {
		this.conditions = conditions;
	}

	public V1alpha2ImageStatus latestBuildImageGeneration(Integer latestBuildImageGeneration) {

		this.latestBuildImageGeneration = latestBuildImageGeneration;
		return this;
	}

	/**
	 * Get latestBuildImageGeneration
	 * @return latestBuildImageGeneration
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public Integer getLatestBuildImageGeneration() {
		return latestBuildImageGeneration;
	}

	public void setLatestBuildImageGeneration(Integer latestBuildImageGeneration) {
		this.latestBuildImageGeneration = latestBuildImageGeneration;
	}

	public V1alpha2ImageStatus latestBuildReason(String latestBuildReason) {

		this.latestBuildReason = latestBuildReason;
		return this;
	}

	/**
	 * Get latestBuildReason
	 * @return latestBuildReason
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getLatestBuildReason() {
		return latestBuildReason;
	}

	public void setLatestBuildReason(String latestBuildReason) {
		this.latestBuildReason = latestBuildReason;
	}

	public V1alpha2ImageStatus latestBuildRef(String latestBuildRef) {

		this.latestBuildRef = latestBuildRef;
		return this;
	}

	/**
	 * Get latestBuildRef
	 * @return latestBuildRef
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getLatestBuildRef() {
		return latestBuildRef;
	}

	public void setLatestBuildRef(String latestBuildRef) {
		this.latestBuildRef = latestBuildRef;
	}

	public V1alpha2ImageStatus latestImage(String latestImage) {

		this.latestImage = latestImage;
		return this;
	}

	/**
	 * Get latestImage
	 * @return latestImage
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getLatestImage() {
		return latestImage;
	}

	public void setLatestImage(String latestImage) {
		this.latestImage = latestImage;
	}

	public V1alpha2ImageStatus latestStack(String latestStack) {

		this.latestStack = latestStack;
		return this;
	}

	/**
	 * Get latestStack
	 * @return latestStack
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getLatestStack() {
		return latestStack;
	}

	public void setLatestStack(String latestStack) {
		this.latestStack = latestStack;
	}

	public V1alpha2ImageStatus observedGeneration(Integer observedGeneration) {

		this.observedGeneration = observedGeneration;
		return this;
	}

	/**
	 * Get observedGeneration
	 * @return observedGeneration
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public Integer getObservedGeneration() {
		return observedGeneration;
	}

	public void setObservedGeneration(Integer observedGeneration) {
		this.observedGeneration = observedGeneration;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		V1alpha2ImageStatus v1alpha2ImageStatus = (V1alpha2ImageStatus) o;
		return Objects.equals(this.buildCacheName, v1alpha2ImageStatus.buildCacheName)
				&& Objects.equals(this.buildCounter, v1alpha2ImageStatus.buildCounter)
				&& Objects.equals(this.conditions, v1alpha2ImageStatus.conditions)
				&& Objects.equals(this.latestBuildImageGeneration, v1alpha2ImageStatus.latestBuildImageGeneration)
				&& Objects.equals(this.latestBuildReason, v1alpha2ImageStatus.latestBuildReason)
				&& Objects.equals(this.latestBuildRef, v1alpha2ImageStatus.latestBuildRef)
				&& Objects.equals(this.latestImage, v1alpha2ImageStatus.latestImage)
				&& Objects.equals(this.latestStack, v1alpha2ImageStatus.latestStack)
				&& Objects.equals(this.observedGeneration, v1alpha2ImageStatus.observedGeneration);
	}

	@Override
	public int hashCode() {
		return Objects.hash(buildCacheName, buildCounter, conditions, latestBuildImageGeneration, latestBuildReason,
				latestBuildRef, latestImage, latestStack, observedGeneration);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class V1alpha2ImageStatus {\n");
		sb.append("    buildCacheName: ").append(toIndentedString(buildCacheName)).append("\n");
		sb.append("    buildCounter: ").append(toIndentedString(buildCounter)).append("\n");
		sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
		sb.append("    latestBuildImageGeneration: ").append(toIndentedString(latestBuildImageGeneration)).append("\n");
		sb.append("    latestBuildReason: ").append(toIndentedString(latestBuildReason)).append("\n");
		sb.append("    latestBuildRef: ").append(toIndentedString(latestBuildRef)).append("\n");
		sb.append("    latestImage: ").append(toIndentedString(latestImage)).append("\n");
		sb.append("    latestStack: ").append(toIndentedString(latestStack)).append("\n");
		sb.append("    observedGeneration: ").append(toIndentedString(observedGeneration)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
