/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.kpack.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kpack.models.V1alpha2ClusterStackStatusBuildImage;
import io.kpack.models.V1alpha2ClusterStackStatusConditions;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1alpha2ClusterStackStatus
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
		date = "2023-03-27T10:41:15.597Z[Etc/UTC]")
public class V1alpha2ClusterStackStatus {

	public static final String SERIALIZED_NAME_BUILD_IMAGE = "buildImage";

	@SerializedName(SERIALIZED_NAME_BUILD_IMAGE)
	private V1alpha2ClusterStackStatusBuildImage buildImage;

	public static final String SERIALIZED_NAME_CONDITIONS = "conditions";

	@SerializedName(SERIALIZED_NAME_CONDITIONS)
	private List<V1alpha2ClusterStackStatusConditions> conditions = null;

	public static final String SERIALIZED_NAME_GROUP_ID = "groupId";

	@SerializedName(SERIALIZED_NAME_GROUP_ID)
	private Integer groupId;

	public static final String SERIALIZED_NAME_ID = "id";

	@SerializedName(SERIALIZED_NAME_ID)
	private String id;

	public static final String SERIALIZED_NAME_MIXINS = "mixins";

	@SerializedName(SERIALIZED_NAME_MIXINS)
	private List<String> mixins = null;

	public static final String SERIALIZED_NAME_OBSERVED_GENERATION = "observedGeneration";

	@SerializedName(SERIALIZED_NAME_OBSERVED_GENERATION)
	private Integer observedGeneration;

	public static final String SERIALIZED_NAME_RUN_IMAGE = "runImage";

	@SerializedName(SERIALIZED_NAME_RUN_IMAGE)
	private V1alpha2ClusterStackStatusBuildImage runImage;

	public static final String SERIALIZED_NAME_USER_ID = "userId";

	@SerializedName(SERIALIZED_NAME_USER_ID)
	private Integer userId;

	public V1alpha2ClusterStackStatus buildImage(V1alpha2ClusterStackStatusBuildImage buildImage) {

		this.buildImage = buildImage;
		return this;
	}

	/**
	 * Get buildImage
	 * @return buildImage
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public V1alpha2ClusterStackStatusBuildImage getBuildImage() {
		return buildImage;
	}

	public void setBuildImage(V1alpha2ClusterStackStatusBuildImage buildImage) {
		this.buildImage = buildImage;
	}

	public V1alpha2ClusterStackStatus conditions(List<V1alpha2ClusterStackStatusConditions> conditions) {

		this.conditions = conditions;
		return this;
	}

	public V1alpha2ClusterStackStatus addConditionsItem(V1alpha2ClusterStackStatusConditions conditionsItem) {
		if (this.conditions == null) {
			this.conditions = new ArrayList<>();
		}
		this.conditions.add(conditionsItem);
		return this;
	}

	/**
	 * Get conditions
	 * @return conditions
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public List<V1alpha2ClusterStackStatusConditions> getConditions() {
		return conditions;
	}

	public void setConditions(List<V1alpha2ClusterStackStatusConditions> conditions) {
		this.conditions = conditions;
	}

	public V1alpha2ClusterStackStatus groupId(Integer groupId) {

		this.groupId = groupId;
		return this;
	}

	/**
	 * Get groupId
	 * @return groupId
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public Integer getGroupId() {
		return groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	public V1alpha2ClusterStackStatus id(String id) {

		this.id = id;
		return this;
	}

	/**
	 * Get id
	 * @return id
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public V1alpha2ClusterStackStatus mixins(List<String> mixins) {

		this.mixins = mixins;
		return this;
	}

	public V1alpha2ClusterStackStatus addMixinsItem(String mixinsItem) {
		if (this.mixins == null) {
			this.mixins = new ArrayList<>();
		}
		this.mixins.add(mixinsItem);
		return this;
	}

	/**
	 * Get mixins
	 * @return mixins
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public List<String> getMixins() {
		return mixins;
	}

	public void setMixins(List<String> mixins) {
		this.mixins = mixins;
	}

	public V1alpha2ClusterStackStatus observedGeneration(Integer observedGeneration) {

		this.observedGeneration = observedGeneration;
		return this;
	}

	/**
	 * Get observedGeneration
	 * @return observedGeneration
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public Integer getObservedGeneration() {
		return observedGeneration;
	}

	public void setObservedGeneration(Integer observedGeneration) {
		this.observedGeneration = observedGeneration;
	}

	public V1alpha2ClusterStackStatus runImage(V1alpha2ClusterStackStatusBuildImage runImage) {

		this.runImage = runImage;
		return this;
	}

	/**
	 * Get runImage
	 * @return runImage
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public V1alpha2ClusterStackStatusBuildImage getRunImage() {
		return runImage;
	}

	public void setRunImage(V1alpha2ClusterStackStatusBuildImage runImage) {
		this.runImage = runImage;
	}

	public V1alpha2ClusterStackStatus userId(Integer userId) {

		this.userId = userId;
		return this;
	}

	/**
	 * Get userId
	 * @return userId
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		V1alpha2ClusterStackStatus v1alpha2ClusterStackStatus = (V1alpha2ClusterStackStatus) o;
		return Objects.equals(this.buildImage, v1alpha2ClusterStackStatus.buildImage)
				&& Objects.equals(this.conditions, v1alpha2ClusterStackStatus.conditions)
				&& Objects.equals(this.groupId, v1alpha2ClusterStackStatus.groupId)
				&& Objects.equals(this.id, v1alpha2ClusterStackStatus.id)
				&& Objects.equals(this.mixins, v1alpha2ClusterStackStatus.mixins)
				&& Objects.equals(this.observedGeneration, v1alpha2ClusterStackStatus.observedGeneration)
				&& Objects.equals(this.runImage, v1alpha2ClusterStackStatus.runImage)
				&& Objects.equals(this.userId, v1alpha2ClusterStackStatus.userId);
	}

	@Override
	public int hashCode() {
		return Objects.hash(buildImage, conditions, groupId, id, mixins, observedGeneration, runImage, userId);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class V1alpha2ClusterStackStatus {\n");
		sb.append("    buildImage: ").append(toIndentedString(buildImage)).append("\n");
		sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
		sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    mixins: ").append(toIndentedString(mixins)).append("\n");
		sb.append("    observedGeneration: ").append(toIndentedString(observedGeneration)).append("\n");
		sb.append("    runImage: ").append(toIndentedString(runImage)).append("\n");
		sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
