/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.vmware.tanzu.buildservice.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.vmware.tanzu.buildservice.models.V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptor;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1alpha1TanzuNetDependencyUpdaterSpec
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
		date = "2023-04-03T05:10:03.423Z[Etc/UTC]")
public class V1alpha1TanzuNetDependencyUpdaterSpec {

	public static final String SERIALIZED_NAME_CHECK_EVERY = "checkEvery";

	@SerializedName(SERIALIZED_NAME_CHECK_EVERY)
	private String checkEvery;

	public static final String SERIALIZED_NAME_DESCRIPTOR_NAME = "descriptorName";

	@SerializedName(SERIALIZED_NAME_DESCRIPTOR_NAME)
	private String descriptorName;

	public static final String SERIALIZED_NAME_INLINE_DESCRIPTOR = "inlineDescriptor";

	@SerializedName(SERIALIZED_NAME_INLINE_DESCRIPTOR)
	private V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptor inlineDescriptor;

	public static final String SERIALIZED_NAME_PRODUCT_SLUG = "productSlug";

	@SerializedName(SERIALIZED_NAME_PRODUCT_SLUG)
	private String productSlug;

	public static final String SERIALIZED_NAME_SERVICE_ACCOUNT_NAME = "serviceAccountName";

	@SerializedName(SERIALIZED_NAME_SERVICE_ACCOUNT_NAME)
	private String serviceAccountName;

	public V1alpha1TanzuNetDependencyUpdaterSpec checkEvery(String checkEvery) {

		this.checkEvery = checkEvery;
		return this;
	}

	/**
	 * Get checkEvery
	 * @return checkEvery
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getCheckEvery() {
		return checkEvery;
	}

	public void setCheckEvery(String checkEvery) {
		this.checkEvery = checkEvery;
	}

	public V1alpha1TanzuNetDependencyUpdaterSpec descriptorName(String descriptorName) {

		this.descriptorName = descriptorName;
		return this;
	}

	/**
	 * Get descriptorName
	 * @return descriptorName
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getDescriptorName() {
		return descriptorName;
	}

	public void setDescriptorName(String descriptorName) {
		this.descriptorName = descriptorName;
	}

	public V1alpha1TanzuNetDependencyUpdaterSpec inlineDescriptor(
			V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptor inlineDescriptor) {

		this.inlineDescriptor = inlineDescriptor;
		return this;
	}

	/**
	 * Get inlineDescriptor
	 * @return inlineDescriptor
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptor getInlineDescriptor() {
		return inlineDescriptor;
	}

	public void setInlineDescriptor(V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptor inlineDescriptor) {
		this.inlineDescriptor = inlineDescriptor;
	}

	public V1alpha1TanzuNetDependencyUpdaterSpec productSlug(String productSlug) {

		this.productSlug = productSlug;
		return this;
	}

	/**
	 * Get productSlug
	 * @return productSlug
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getProductSlug() {
		return productSlug;
	}

	public void setProductSlug(String productSlug) {
		this.productSlug = productSlug;
	}

	public V1alpha1TanzuNetDependencyUpdaterSpec serviceAccountName(String serviceAccountName) {

		this.serviceAccountName = serviceAccountName;
		return this;
	}

	/**
	 * Get serviceAccountName
	 * @return serviceAccountName
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getServiceAccountName() {
		return serviceAccountName;
	}

	public void setServiceAccountName(String serviceAccountName) {
		this.serviceAccountName = serviceAccountName;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		V1alpha1TanzuNetDependencyUpdaterSpec v1alpha1TanzuNetDependencyUpdaterSpec = (V1alpha1TanzuNetDependencyUpdaterSpec) o;
		return Objects.equals(this.checkEvery, v1alpha1TanzuNetDependencyUpdaterSpec.checkEvery)
				&& Objects.equals(this.descriptorName, v1alpha1TanzuNetDependencyUpdaterSpec.descriptorName)
				&& Objects.equals(this.inlineDescriptor, v1alpha1TanzuNetDependencyUpdaterSpec.inlineDescriptor)
				&& Objects.equals(this.productSlug, v1alpha1TanzuNetDependencyUpdaterSpec.productSlug)
				&& Objects.equals(this.serviceAccountName, v1alpha1TanzuNetDependencyUpdaterSpec.serviceAccountName);
	}

	@Override
	public int hashCode() {
		return Objects.hash(checkEvery, descriptorName, inlineDescriptor, productSlug, serviceAccountName);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class V1alpha1TanzuNetDependencyUpdaterSpec {\n");
		sb.append("    checkEvery: ").append(toIndentedString(checkEvery)).append("\n");
		sb.append("    descriptorName: ").append(toIndentedString(descriptorName)).append("\n");
		sb.append("    inlineDescriptor: ").append(toIndentedString(inlineDescriptor)).append("\n");
		sb.append("    productSlug: ").append(toIndentedString(productSlug)).append("\n");
		sb.append("    serviceAccountName: ").append(toIndentedString(serviceAccountName)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
