/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.vmware.tanzu.buildservice.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.vmware.tanzu.buildservice.models.V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorOrder;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterBuilders
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
		date = "2023-04-03T05:10:03.423Z[Etc/UTC]")
public class V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterBuilders {

	public static final String SERIALIZED_NAME_CLUSTER_STACK = "clusterStack";

	@SerializedName(SERIALIZED_NAME_CLUSTER_STACK)
	private String clusterStack;

	public static final String SERIALIZED_NAME_CLUSTER_STORE = "clusterStore";

	@SerializedName(SERIALIZED_NAME_CLUSTER_STORE)
	private String clusterStore;

	public static final String SERIALIZED_NAME_NAME = "name";

	@SerializedName(SERIALIZED_NAME_NAME)
	private String name;

	public static final String SERIALIZED_NAME_ORDER = "order";

	@SerializedName(SERIALIZED_NAME_ORDER)
	private List<V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorOrder> order = null;

	public V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterBuilders clusterStack(String clusterStack) {

		this.clusterStack = clusterStack;
		return this;
	}

	/**
	 * Get clusterStack
	 * @return clusterStack
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getClusterStack() {
		return clusterStack;
	}

	public void setClusterStack(String clusterStack) {
		this.clusterStack = clusterStack;
	}

	public V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterBuilders clusterStore(String clusterStore) {

		this.clusterStore = clusterStore;
		return this;
	}

	/**
	 * Get clusterStore
	 * @return clusterStore
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getClusterStore() {
		return clusterStore;
	}

	public void setClusterStore(String clusterStore) {
		this.clusterStore = clusterStore;
	}

	public V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterBuilders name(String name) {

		this.name = name;
		return this;
	}

	/**
	 * Get name
	 * @return name
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterBuilders order(
			List<V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorOrder> order) {

		this.order = order;
		return this;
	}

	public V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterBuilders addOrderItem(
			V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorOrder orderItem) {
		if (this.order == null) {
			this.order = new ArrayList<>();
		}
		this.order.add(orderItem);
		return this;
	}

	/**
	 * Get order
	 * @return order
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public List<V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorOrder> getOrder() {
		return order;
	}

	public void setOrder(List<V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorOrder> order) {
		this.order = order;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterBuilders v1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterBuilders = (V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterBuilders) o;
		return Objects.equals(this.clusterStack,
				v1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterBuilders.clusterStack)
				&& Objects.equals(this.clusterStore,
						v1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterBuilders.clusterStore)
				&& Objects.equals(this.name, v1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterBuilders.name)
				&& Objects.equals(this.order,
						v1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterBuilders.order);
	}

	@Override
	public int hashCode() {
		return Objects.hash(clusterStack, clusterStore, name, order);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterBuilders {\n");
		sb.append("    clusterStack: ").append(toIndentedString(clusterStack)).append("\n");
		sb.append("    clusterStore: ").append(toIndentedString(clusterStore)).append("\n");
		sb.append("    name: ").append(toIndentedString(name)).append("\n");
		sb.append("    order: ").append(toIndentedString(order)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
