/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.vmware.tanzu.buildservice.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.vmware.tanzu.buildservice.models.V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorBuildImage;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterStacks
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
		date = "2023-04-03T05:10:03.423Z[Etc/UTC]")
public class V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterStacks {

	public static final String SERIALIZED_NAME_BUILD_IMAGE = "buildImage";

	@SerializedName(SERIALIZED_NAME_BUILD_IMAGE)
	private V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorBuildImage buildImage;

	public static final String SERIALIZED_NAME_NAME = "name";

	@SerializedName(SERIALIZED_NAME_NAME)
	private String name;

	public static final String SERIALIZED_NAME_RUN_IMAGE = "runImage";

	@SerializedName(SERIALIZED_NAME_RUN_IMAGE)
	private V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorBuildImage runImage;

	public V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterStacks buildImage(
			V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorBuildImage buildImage) {

		this.buildImage = buildImage;
		return this;
	}

	/**
	 * Get buildImage
	 * @return buildImage
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorBuildImage getBuildImage() {
		return buildImage;
	}

	public void setBuildImage(V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorBuildImage buildImage) {
		this.buildImage = buildImage;
	}

	public V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterStacks name(String name) {

		this.name = name;
		return this;
	}

	/**
	 * Get name
	 * @return name
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterStacks runImage(
			V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorBuildImage runImage) {

		this.runImage = runImage;
		return this;
	}

	/**
	 * Get runImage
	 * @return runImage
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorBuildImage getRunImage() {
		return runImage;
	}

	public void setRunImage(V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorBuildImage runImage) {
		this.runImage = runImage;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterStacks v1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterStacks = (V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterStacks) o;
		return Objects.equals(this.buildImage,
				v1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterStacks.buildImage)
				&& Objects.equals(this.name, v1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterStacks.name)
				&& Objects.equals(this.runImage,
						v1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterStacks.runImage);
	}

	@Override
	public int hashCode() {
		return Objects.hash(buildImage, name, runImage);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterStacks {\n");
		sb.append("    buildImage: ").append(toIndentedString(buildImage)).append("\n");
		sb.append("    name: ").append(toIndentedString(name)).append("\n");
		sb.append("    runImage: ").append(toIndentedString(runImage)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
