/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.vmware.tanzu.buildservice.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.vmware.tanzu.buildservice.models.V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorBuildImage;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterStores
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
		date = "2023-04-03T05:10:03.423Z[Etc/UTC]")
public class V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterStores {

	public static final String SERIALIZED_NAME_NAME = "name";

	@SerializedName(SERIALIZED_NAME_NAME)
	private String name;

	public static final String SERIALIZED_NAME_SOURCES = "sources";

	@SerializedName(SERIALIZED_NAME_SOURCES)
	private List<V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorBuildImage> sources = null;

	public V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterStores name(String name) {

		this.name = name;
		return this;
	}

	/**
	 * Get name
	 * @return name
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterStores sources(
			List<V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorBuildImage> sources) {

		this.sources = sources;
		return this;
	}

	public V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterStores addSourcesItem(
			V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorBuildImage sourcesItem) {
		if (this.sources == null) {
			this.sources = new ArrayList<>();
		}
		this.sources.add(sourcesItem);
		return this;
	}

	/**
	 * Get sources
	 * @return sources
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public List<V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorBuildImage> getSources() {
		return sources;
	}

	public void setSources(List<V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorBuildImage> sources) {
		this.sources = sources;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterStores v1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterStores = (V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterStores) o;
		return Objects.equals(this.name, v1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterStores.name)
				&& Objects.equals(this.sources,
						v1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterStores.sources);
	}

	@Override
	public int hashCode() {
		return Objects.hash(name, sources);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class V1alpha1TanzuNetDependencyUpdaterSpecInlineDescriptorClusterStores {\n");
		sb.append("    name: ").append(toIndentedString(name)).append("\n");
		sb.append("    sources: ").append(toIndentedString(sources)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
