/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.vmware.tanzu.stacksoperator.stacks.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1alpha1CustomStackSpecUser
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
		date = "2023-05-25T02:55:10.964Z[Etc/UTC]")
public class V1alpha1CustomStackSpecUser {

	public static final String SERIALIZED_NAME_GROUP_I_D = "groupID";

	@SerializedName(SERIALIZED_NAME_GROUP_I_D)
	private Integer groupID;

	public static final String SERIALIZED_NAME_USER_I_D = "userID";

	@SerializedName(SERIALIZED_NAME_USER_I_D)
	private Integer userID;

	public V1alpha1CustomStackSpecUser groupID(Integer groupID) {

		this.groupID = groupID;
		return this;
	}

	/**
	 * Get groupID
	 * @return groupID
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public Integer getGroupID() {
		return groupID;
	}

	public void setGroupID(Integer groupID) {
		this.groupID = groupID;
	}

	public V1alpha1CustomStackSpecUser userID(Integer userID) {

		this.userID = userID;
		return this;
	}

	/**
	 * Get userID
	 * @return userID
	 **/
	@ApiModelProperty(required = true, value = "")

	public Integer getUserID() {
		return userID;
	}

	public void setUserID(Integer userID) {
		this.userID = userID;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		V1alpha1CustomStackSpecUser v1alpha1CustomStackSpecUser = (V1alpha1CustomStackSpecUser) o;
		return Objects.equals(this.groupID, v1alpha1CustomStackSpecUser.groupID)
				&& Objects.equals(this.userID, v1alpha1CustomStackSpecUser.userID);
	}

	@Override
	public int hashCode() {
		return Objects.hash(groupID, userID);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class V1alpha1CustomStackSpecUser {\n");
		sb.append("    groupID: ").append(toIndentedString(groupID)).append("\n");
		sb.append("    userID: ").append(toIndentedString(userID)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
