/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.vmware.tanzu.stacksoperator.stacks.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1alpha1CustomStackSpecSourceStack
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
		date = "2023-05-25T02:55:10.964Z[Etc/UTC]")
public class V1alpha1CustomStackSpecSourceStack {

	public static final String SERIALIZED_NAME_API_VERSION = "apiVersion";

	@SerializedName(SERIALIZED_NAME_API_VERSION)
	private String apiVersion;

	public static final String SERIALIZED_NAME_FIELD_PATH = "fieldPath";

	@SerializedName(SERIALIZED_NAME_FIELD_PATH)
	private String fieldPath;

	public static final String SERIALIZED_NAME_KIND = "kind";

	@SerializedName(SERIALIZED_NAME_KIND)
	private String kind;

	public static final String SERIALIZED_NAME_NAME = "name";

	@SerializedName(SERIALIZED_NAME_NAME)
	private String name;

	public static final String SERIALIZED_NAME_NAMESPACE = "namespace";

	@SerializedName(SERIALIZED_NAME_NAMESPACE)
	private String namespace;

	public static final String SERIALIZED_NAME_RESOURCE_VERSION = "resourceVersion";

	@SerializedName(SERIALIZED_NAME_RESOURCE_VERSION)
	private String resourceVersion;

	public static final String SERIALIZED_NAME_UID = "uid";

	@SerializedName(SERIALIZED_NAME_UID)
	private String uid;

	public V1alpha1CustomStackSpecSourceStack apiVersion(String apiVersion) {

		this.apiVersion = apiVersion;
		return this;
	}

	/**
	 * API version of the referent.
	 * @return apiVersion
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "API version of the referent.")

	public String getApiVersion() {
		return apiVersion;
	}

	public void setApiVersion(String apiVersion) {
		this.apiVersion = apiVersion;
	}

	public V1alpha1CustomStackSpecSourceStack fieldPath(String fieldPath) {

		this.fieldPath = fieldPath;
		return this;
	}

	/**
	 * Get fieldPath
	 * @return fieldPath
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getFieldPath() {
		return fieldPath;
	}

	public void setFieldPath(String fieldPath) {
		this.fieldPath = fieldPath;
	}

	public V1alpha1CustomStackSpecSourceStack kind(String kind) {

		this.kind = kind;
		return this;
	}

	/**
	 * Get kind
	 * @return kind
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getKind() {
		return kind;
	}

	public void setKind(String kind) {
		this.kind = kind;
	}

	public V1alpha1CustomStackSpecSourceStack name(String name) {

		this.name = name;
		return this;
	}

	/**
	 * Get name
	 * @return name
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public V1alpha1CustomStackSpecSourceStack namespace(String namespace) {

		this.namespace = namespace;
		return this;
	}

	/**
	 * Get namespace
	 * @return namespace
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getNamespace() {
		return namespace;
	}

	public void setNamespace(String namespace) {
		this.namespace = namespace;
	}

	public V1alpha1CustomStackSpecSourceStack resourceVersion(String resourceVersion) {

		this.resourceVersion = resourceVersion;
		return this;
	}

	/**
	 * Get resourceVersion
	 * @return resourceVersion
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getResourceVersion() {
		return resourceVersion;
	}

	public void setResourceVersion(String resourceVersion) {
		this.resourceVersion = resourceVersion;
	}

	public V1alpha1CustomStackSpecSourceStack uid(String uid) {

		this.uid = uid;
		return this;
	}

	/**
	 * Get uid
	 * @return uid
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getUid() {
		return uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		V1alpha1CustomStackSpecSourceStack v1alpha1CustomStackSpecSourceStack = (V1alpha1CustomStackSpecSourceStack) o;
		return Objects.equals(this.apiVersion, v1alpha1CustomStackSpecSourceStack.apiVersion)
				&& Objects.equals(this.fieldPath, v1alpha1CustomStackSpecSourceStack.fieldPath)
				&& Objects.equals(this.kind, v1alpha1CustomStackSpecSourceStack.kind)
				&& Objects.equals(this.name, v1alpha1CustomStackSpecSourceStack.name)
				&& Objects.equals(this.namespace, v1alpha1CustomStackSpecSourceStack.namespace)
				&& Objects.equals(this.resourceVersion, v1alpha1CustomStackSpecSourceStack.resourceVersion)
				&& Objects.equals(this.uid, v1alpha1CustomStackSpecSourceStack.uid);
	}

	@Override
	public int hashCode() {
		return Objects.hash(apiVersion, fieldPath, kind, name, namespace, resourceVersion, uid);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class V1alpha1CustomStackSpecSourceStack {\n");
		sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
		sb.append("    fieldPath: ").append(toIndentedString(fieldPath)).append("\n");
		sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
		sb.append("    name: ").append(toIndentedString(name)).append("\n");
		sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
		sb.append("    resourceVersion: ").append(toIndentedString(resourceVersion)).append("\n");
		sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
