/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.vmware.tanzu.stacksoperator.stacks.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.vmware.tanzu.stacksoperator.stacks.models.V1alpha1CustomStackSpecCaCerts;
import com.vmware.tanzu.stacksoperator.stacks.models.V1alpha1CustomStackSpecDestination;
import com.vmware.tanzu.stacksoperator.stacks.models.V1alpha1CustomStackSpecMixins;
import com.vmware.tanzu.stacksoperator.stacks.models.V1alpha1CustomStackSpecSource;
import com.vmware.tanzu.stacksoperator.stacks.models.V1alpha1CustomStackSpecUser;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1alpha1CustomStackSpec
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
		date = "2023-05-25T02:55:10.964Z[Etc/UTC]")
public class V1alpha1CustomStackSpec {

	public static final String SERIALIZED_NAME_CA_CERTS = "caCerts";

	@SerializedName(SERIALIZED_NAME_CA_CERTS)
	private V1alpha1CustomStackSpecCaCerts caCerts;

	public static final String SERIALIZED_NAME_DESTINATION = "destination";

	@SerializedName(SERIALIZED_NAME_DESTINATION)
	private V1alpha1CustomStackSpecDestination destination;

	public static final String SERIALIZED_NAME_MIXINS = "mixins";

	@SerializedName(SERIALIZED_NAME_MIXINS)
	private List<V1alpha1CustomStackSpecMixins> mixins = null;

	public static final String SERIALIZED_NAME_PACKAGES = "packages";

	@SerializedName(SERIALIZED_NAME_PACKAGES)
	private List<V1alpha1CustomStackSpecMixins> packages = null;

	public static final String SERIALIZED_NAME_SERVICE_ACCOUNT_NAME = "serviceAccountName";

	@SerializedName(SERIALIZED_NAME_SERVICE_ACCOUNT_NAME)
	private String serviceAccountName;

	public static final String SERIALIZED_NAME_SOURCE = "source";

	@SerializedName(SERIALIZED_NAME_SOURCE)
	private V1alpha1CustomStackSpecSource source;

	public static final String SERIALIZED_NAME_USER = "user";

	@SerializedName(SERIALIZED_NAME_USER)
	private V1alpha1CustomStackSpecUser user;

	public V1alpha1CustomStackSpec caCerts(V1alpha1CustomStackSpecCaCerts caCerts) {

		this.caCerts = caCerts;
		return this;
	}

	/**
	 * Get caCerts
	 * @return caCerts
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public V1alpha1CustomStackSpecCaCerts getCaCerts() {
		return caCerts;
	}

	public void setCaCerts(V1alpha1CustomStackSpecCaCerts caCerts) {
		this.caCerts = caCerts;
	}

	public V1alpha1CustomStackSpec destination(V1alpha1CustomStackSpecDestination destination) {

		this.destination = destination;
		return this;
	}

	/**
	 * Get destination
	 * @return destination
	 **/
	@ApiModelProperty(required = true, value = "")

	public V1alpha1CustomStackSpecDestination getDestination() {
		return destination;
	}

	public void setDestination(V1alpha1CustomStackSpecDestination destination) {
		this.destination = destination;
	}

	public V1alpha1CustomStackSpec mixins(List<V1alpha1CustomStackSpecMixins> mixins) {

		this.mixins = mixins;
		return this;
	}

	public V1alpha1CustomStackSpec addMixinsItem(V1alpha1CustomStackSpecMixins mixinsItem) {
		if (this.mixins == null) {
			this.mixins = new ArrayList<>();
		}
		this.mixins.add(mixinsItem);
		return this;
	}

	/**
	 * Get mixins
	 * @return mixins
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public List<V1alpha1CustomStackSpecMixins> getMixins() {
		return mixins;
	}

	public void setMixins(List<V1alpha1CustomStackSpecMixins> mixins) {
		this.mixins = mixins;
	}

	public V1alpha1CustomStackSpec packages(List<V1alpha1CustomStackSpecMixins> packages) {

		this.packages = packages;
		return this;
	}

	public V1alpha1CustomStackSpec addPackagesItem(V1alpha1CustomStackSpecMixins packagesItem) {
		if (this.packages == null) {
			this.packages = new ArrayList<>();
		}
		this.packages.add(packagesItem);
		return this;
	}

	/**
	 * Get packages
	 * @return packages
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public List<V1alpha1CustomStackSpecMixins> getPackages() {
		return packages;
	}

	public void setPackages(List<V1alpha1CustomStackSpecMixins> packages) {
		this.packages = packages;
	}

	public V1alpha1CustomStackSpec serviceAccountName(String serviceAccountName) {

		this.serviceAccountName = serviceAccountName;
		return this;
	}

	/**
	 * Get serviceAccountName
	 * @return serviceAccountName
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getServiceAccountName() {
		return serviceAccountName;
	}

	public void setServiceAccountName(String serviceAccountName) {
		this.serviceAccountName = serviceAccountName;
	}

	public V1alpha1CustomStackSpec source(V1alpha1CustomStackSpecSource source) {

		this.source = source;
		return this;
	}

	/**
	 * Get source
	 * @return source
	 **/
	@ApiModelProperty(required = true, value = "")

	public V1alpha1CustomStackSpecSource getSource() {
		return source;
	}

	public void setSource(V1alpha1CustomStackSpecSource source) {
		this.source = source;
	}

	public V1alpha1CustomStackSpec user(V1alpha1CustomStackSpecUser user) {

		this.user = user;
		return this;
	}

	/**
	 * Get user
	 * @return user
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public V1alpha1CustomStackSpecUser getUser() {
		return user;
	}

	public void setUser(V1alpha1CustomStackSpecUser user) {
		this.user = user;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		V1alpha1CustomStackSpec v1alpha1CustomStackSpec = (V1alpha1CustomStackSpec) o;
		return Objects.equals(this.caCerts, v1alpha1CustomStackSpec.caCerts)
				&& Objects.equals(this.destination, v1alpha1CustomStackSpec.destination)
				&& Objects.equals(this.mixins, v1alpha1CustomStackSpec.mixins)
				&& Objects.equals(this.packages, v1alpha1CustomStackSpec.packages)
				&& Objects.equals(this.serviceAccountName, v1alpha1CustomStackSpec.serviceAccountName)
				&& Objects.equals(this.source, v1alpha1CustomStackSpec.source)
				&& Objects.equals(this.user, v1alpha1CustomStackSpec.user);
	}

	@Override
	public int hashCode() {
		return Objects.hash(caCerts, destination, mixins, packages, serviceAccountName, source, user);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class V1alpha1CustomStackSpec {\n");
		sb.append("    caCerts: ").append(toIndentedString(caCerts)).append("\n");
		sb.append("    destination: ").append(toIndentedString(destination)).append("\n");
		sb.append("    mixins: ").append(toIndentedString(mixins)).append("\n");
		sb.append("    packages: ").append(toIndentedString(packages)).append("\n");
		sb.append("    serviceAccountName: ").append(toIndentedString(serviceAccountName)).append("\n");
		sb.append("    source: ").append(toIndentedString(source)).append("\n");
		sb.append("    user: ").append(toIndentedString(user)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
