/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.vmware.tanzu.stacksoperator.stacks.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1alpha1CustomStackSpecMixins
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
		date = "2023-05-25T02:55:10.964Z[Etc/UTC]")
public class V1alpha1CustomStackSpecMixins {

	public static final String SERIALIZED_NAME_NAME = "name";

	@SerializedName(SERIALIZED_NAME_NAME)
	private String name;

	public static final String SERIALIZED_NAME_PHASE = "phase";

	@SerializedName(SERIALIZED_NAME_PHASE)
	private String phase;

	public V1alpha1CustomStackSpecMixins name(String name) {

		this.name = name;
		return this;
	}

	/**
	 * Get name
	 * @return name
	 **/
	@ApiModelProperty(required = true, value = "")

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public V1alpha1CustomStackSpecMixins phase(String phase) {

		this.phase = phase;
		return this;
	}

	/**
	 * Get phase
	 * @return phase
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getPhase() {
		return phase;
	}

	public void setPhase(String phase) {
		this.phase = phase;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		V1alpha1CustomStackSpecMixins v1alpha1CustomStackSpecMixins = (V1alpha1CustomStackSpecMixins) o;
		return Objects.equals(this.name, v1alpha1CustomStackSpecMixins.name)
				&& Objects.equals(this.phase, v1alpha1CustomStackSpecMixins.phase);
	}

	@Override
	public int hashCode() {
		return Objects.hash(name, phase);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class V1alpha1CustomStackSpecMixins {\n");
		sb.append("    name: ").append(toIndentedString(name)).append("\n");
		sb.append("    phase: ").append(toIndentedString(phase)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
