/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.vmware.tanzu.stacksoperator.stacks.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.vmware.tanzu.stacksoperator.stacks.models.V1alpha1CustomStackSpecDestinationBuild;
import com.vmware.tanzu.stacksoperator.stacks.models.V1alpha1CustomStackSpecDestinationStack;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1alpha1CustomStackSpecDestination
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
		date = "2023-05-25T02:55:10.964Z[Etc/UTC]")
public class V1alpha1CustomStackSpecDestination {

	public static final String SERIALIZED_NAME_BUILD = "build";

	@SerializedName(SERIALIZED_NAME_BUILD)
	private V1alpha1CustomStackSpecDestinationBuild build;

	public static final String SERIALIZED_NAME_RUN = "run";

	@SerializedName(SERIALIZED_NAME_RUN)
	private V1alpha1CustomStackSpecDestinationBuild run;

	public static final String SERIALIZED_NAME_STACK = "stack";

	@SerializedName(SERIALIZED_NAME_STACK)
	private V1alpha1CustomStackSpecDestinationStack stack;

	public V1alpha1CustomStackSpecDestination build(V1alpha1CustomStackSpecDestinationBuild build) {

		this.build = build;
		return this;
	}

	/**
	 * Get build
	 * @return build
	 **/
	@ApiModelProperty(required = true, value = "")

	public V1alpha1CustomStackSpecDestinationBuild getBuild() {
		return build;
	}

	public void setBuild(V1alpha1CustomStackSpecDestinationBuild build) {
		this.build = build;
	}

	public V1alpha1CustomStackSpecDestination run(V1alpha1CustomStackSpecDestinationBuild run) {

		this.run = run;
		return this;
	}

	/**
	 * Get run
	 * @return run
	 **/
	@ApiModelProperty(required = true, value = "")

	public V1alpha1CustomStackSpecDestinationBuild getRun() {
		return run;
	}

	public void setRun(V1alpha1CustomStackSpecDestinationBuild run) {
		this.run = run;
	}

	public V1alpha1CustomStackSpecDestination stack(V1alpha1CustomStackSpecDestinationStack stack) {

		this.stack = stack;
		return this;
	}

	/**
	 * Get stack
	 * @return stack
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public V1alpha1CustomStackSpecDestinationStack getStack() {
		return stack;
	}

	public void setStack(V1alpha1CustomStackSpecDestinationStack stack) {
		this.stack = stack;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		V1alpha1CustomStackSpecDestination v1alpha1CustomStackSpecDestination = (V1alpha1CustomStackSpecDestination) o;
		return Objects.equals(this.build, v1alpha1CustomStackSpecDestination.build)
				&& Objects.equals(this.run, v1alpha1CustomStackSpecDestination.run)
				&& Objects.equals(this.stack, v1alpha1CustomStackSpecDestination.stack);
	}

	@Override
	public int hashCode() {
		return Objects.hash(build, run, stack);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class V1alpha1CustomStackSpecDestination {\n");
		sb.append("    build: ").append(toIndentedString(build)).append("\n");
		sb.append("    run: ").append(toIndentedString(run)).append("\n");
		sb.append("    stack: ").append(toIndentedString(stack)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
