/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.vmware.tanzu.stacksoperator.stacks.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.vmware.tanzu.stacksoperator.stacks.models.V1alpha1CustomStackStatusConditions;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * V1alpha1CustomStackStatus
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
		date = "2023-05-25T02:55:10.964Z[Etc/UTC]")
public class V1alpha1CustomStackStatus {

	public static final String SERIALIZED_NAME_BASE_BUILD_IMAGE = "baseBuildImage";

	@SerializedName(SERIALIZED_NAME_BASE_BUILD_IMAGE)
	private String baseBuildImage;

	public static final String SERIALIZED_NAME_BASE_RUN_IMAGE = "baseRunImage";

	@SerializedName(SERIALIZED_NAME_BASE_RUN_IMAGE)
	private String baseRunImage;

	public static final String SERIALIZED_NAME_BUILD_IMAGE = "buildImage";

	@SerializedName(SERIALIZED_NAME_BUILD_IMAGE)
	private String buildImage;

	public static final String SERIALIZED_NAME_CONDITIONS = "conditions";

	@SerializedName(SERIALIZED_NAME_CONDITIONS)
	private List<V1alpha1CustomStackStatusConditions> conditions = null;

	public static final String SERIALIZED_NAME_ID = "id";

	@SerializedName(SERIALIZED_NAME_ID)
	private String id;

	public static final String SERIALIZED_NAME_LAST_BUILD_TIME = "lastBuildTime";

	@SerializedName(SERIALIZED_NAME_LAST_BUILD_TIME)
	private OffsetDateTime lastBuildTime;

	public static final String SERIALIZED_NAME_RUN_IMAGE = "runImage";

	@SerializedName(SERIALIZED_NAME_RUN_IMAGE)
	private String runImage;

	public V1alpha1CustomStackStatus baseBuildImage(String baseBuildImage) {

		this.baseBuildImage = baseBuildImage;
		return this;
	}

	/**
	 * Get baseBuildImage
	 * @return baseBuildImage
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getBaseBuildImage() {
		return baseBuildImage;
	}

	public void setBaseBuildImage(String baseBuildImage) {
		this.baseBuildImage = baseBuildImage;
	}

	public V1alpha1CustomStackStatus baseRunImage(String baseRunImage) {

		this.baseRunImage = baseRunImage;
		return this;
	}

	/**
	 * Get baseRunImage
	 * @return baseRunImage
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getBaseRunImage() {
		return baseRunImage;
	}

	public void setBaseRunImage(String baseRunImage) {
		this.baseRunImage = baseRunImage;
	}

	public V1alpha1CustomStackStatus buildImage(String buildImage) {

		this.buildImage = buildImage;
		return this;
	}

	/**
	 * Get buildImage
	 * @return buildImage
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getBuildImage() {
		return buildImage;
	}

	public void setBuildImage(String buildImage) {
		this.buildImage = buildImage;
	}

	public V1alpha1CustomStackStatus conditions(List<V1alpha1CustomStackStatusConditions> conditions) {

		this.conditions = conditions;
		return this;
	}

	public V1alpha1CustomStackStatus addConditionsItem(V1alpha1CustomStackStatusConditions conditionsItem) {
		if (this.conditions == null) {
			this.conditions = new ArrayList<>();
		}
		this.conditions.add(conditionsItem);
		return this;
	}

	/**
	 * Get conditions
	 * @return conditions
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public List<V1alpha1CustomStackStatusConditions> getConditions() {
		return conditions;
	}

	public void setConditions(List<V1alpha1CustomStackStatusConditions> conditions) {
		this.conditions = conditions;
	}

	public V1alpha1CustomStackStatus id(String id) {

		this.id = id;
		return this;
	}

	/**
	 * Get id
	 * @return id
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public V1alpha1CustomStackStatus lastBuildTime(OffsetDateTime lastBuildTime) {

		this.lastBuildTime = lastBuildTime;
		return this;
	}

	/**
	 * Get lastBuildTime
	 * @return lastBuildTime
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public OffsetDateTime getLastBuildTime() {
		return lastBuildTime;
	}

	public void setLastBuildTime(OffsetDateTime lastBuildTime) {
		this.lastBuildTime = lastBuildTime;
	}

	public V1alpha1CustomStackStatus runImage(String runImage) {

		this.runImage = runImage;
		return this;
	}

	/**
	 * Get runImage
	 * @return runImage
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public String getRunImage() {
		return runImage;
	}

	public void setRunImage(String runImage) {
		this.runImage = runImage;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		V1alpha1CustomStackStatus v1alpha1CustomStackStatus = (V1alpha1CustomStackStatus) o;
		return Objects.equals(this.baseBuildImage, v1alpha1CustomStackStatus.baseBuildImage)
				&& Objects.equals(this.baseRunImage, v1alpha1CustomStackStatus.baseRunImage)
				&& Objects.equals(this.buildImage, v1alpha1CustomStackStatus.buildImage)
				&& Objects.equals(this.conditions, v1alpha1CustomStackStatus.conditions)
				&& Objects.equals(this.id, v1alpha1CustomStackStatus.id)
				&& Objects.equals(this.lastBuildTime, v1alpha1CustomStackStatus.lastBuildTime)
				&& Objects.equals(this.runImage, v1alpha1CustomStackStatus.runImage);
	}

	@Override
	public int hashCode() {
		return Objects.hash(baseBuildImage, baseRunImage, buildImage, conditions, id, lastBuildTime, runImage);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class V1alpha1CustomStackStatus {\n");
		sb.append("    baseBuildImage: ").append(toIndentedString(baseBuildImage)).append("\n");
		sb.append("    baseRunImage: ").append(toIndentedString(baseRunImage)).append("\n");
		sb.append("    buildImage: ").append(toIndentedString(buildImage)).append("\n");
		sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    lastBuildTime: ").append(toIndentedString(lastBuildTime)).append("\n");
		sb.append("    runImage: ").append(toIndentedString(runImage)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
