/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.vmware.tanzu.stacksoperator.stacks.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.vmware.tanzu.stacksoperator.stacks.models.V1alpha1CustomStackSpecCaCertsBuildRef;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1alpha1CustomStackSpecCaCerts
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
		date = "2023-05-25T02:55:10.964Z[Etc/UTC]")
public class V1alpha1CustomStackSpecCaCerts {

	public static final String SERIALIZED_NAME_BUILD_REF = "buildRef";

	@SerializedName(SERIALIZED_NAME_BUILD_REF)
	private V1alpha1CustomStackSpecCaCertsBuildRef buildRef;

	public static final String SERIALIZED_NAME_RUN_REF = "runRef";

	@SerializedName(SERIALIZED_NAME_RUN_REF)
	private V1alpha1CustomStackSpecCaCertsBuildRef runRef;

	public V1alpha1CustomStackSpecCaCerts buildRef(V1alpha1CustomStackSpecCaCertsBuildRef buildRef) {

		this.buildRef = buildRef;
		return this;
	}

	/**
	 * Get buildRef
	 * @return buildRef
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public V1alpha1CustomStackSpecCaCertsBuildRef getBuildRef() {
		return buildRef;
	}

	public void setBuildRef(V1alpha1CustomStackSpecCaCertsBuildRef buildRef) {
		this.buildRef = buildRef;
	}

	public V1alpha1CustomStackSpecCaCerts runRef(V1alpha1CustomStackSpecCaCertsBuildRef runRef) {

		this.runRef = runRef;
		return this;
	}

	/**
	 * Get runRef
	 * @return runRef
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")

	public V1alpha1CustomStackSpecCaCertsBuildRef getRunRef() {
		return runRef;
	}

	public void setRunRef(V1alpha1CustomStackSpecCaCertsBuildRef runRef) {
		this.runRef = runRef;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		V1alpha1CustomStackSpecCaCerts v1alpha1CustomStackSpecCaCerts = (V1alpha1CustomStackSpecCaCerts) o;
		return Objects.equals(this.buildRef, v1alpha1CustomStackSpecCaCerts.buildRef)
				&& Objects.equals(this.runRef, v1alpha1CustomStackSpecCaCerts.runRef);
	}

	@Override
	public int hashCode() {
		return Objects.hash(buildRef, runRef);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class V1alpha1CustomStackSpecCaCerts {\n");
		sb.append("    buildRef: ").append(toIndentedString(buildRef)).append("\n");
		sb.append("    runRef: ").append(toIndentedString(runRef)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
