apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: kpack-exporter.pkg.maki.lol.0.0.1
spec:
  refName: kpack-exporter.pkg.maki.lol
  version: 0.0.1
  releaseNotes: kpack exporter 0.0.1
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        namespace:
          type: string
          description: namespace where kpack-exporter server is installed
          default: kpack-exporter
        create_namespace:
          type: boolean
          description: whether to create the namespace
          default: true
        env:
          type: array
          description: Extra env to the code server
          items:
            nullable: true
            description: name and value of an environment variable
            default: {}
          default: []
        builtin_alert:
          type: object
          additionalProperties: false
          description: Configurations for built-in alert
          properties:
            enabled:
              type: boolean
              description: whether to enable the built-in alert
              default: false
            debug:
              type: boolean
              description: whether to enable the debug logs for built-in alert
              default: false
            type:
              type: string
              description: Webhook type
              default: slack
            webhook_url:
              type: string
              description: Webhook URL
              default: ""
            cluster:
              type: string
              description: Cluster name
              default: ""
            slack:
              type: object
              additionalProperties: false
              description: Configurations for slack webhook
              properties:
                channel:
                  type: string
                  description: Slack channel
                  default: ""
            generic:
              type: object
              additionalProperties: false
              description: Configurations for generic webhook
              properties:
                template:
                  type: string
                  description: Template of the payload
                  default: |-
                    {
                      "result": "${RESULT}",
                      "kind": "${KIND}",
                      "namespace": "${NAMESPACE}",
                      "name": "${NAME}",
                      "cluster": "${CLUSTER}",
                      "text": "${TEXT}"
                    }
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: ghcr.io/making/kpack-exporter-bundle:0.0.1
      template:
      - ytt: {}
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
          - --diff-changes=true
          - --diff-mask=false
          inspect: {}
