name: Java CI with Maven

on:
  push:
    branches:
    - develop
    - main
    paths:
    - src/**
    - pom.xml
    - .github/workflows/ci.yaml
  pull_request:
    branches:
    - develop
    - main
    paths:
    - src/**
    - pom.xml
    - .github/workflows/ci.yaml
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Import Secrets
      id: secrets
      uses: hashicorp/vault-action@v2.5.0
      with:
        exportToken: true
        exportEnv: true
        method: jwt
        url: ${{ secrets.VAULT_ADDR }}
        role: cicd
        secrets: |
          kv/data/cicd/sonatype username | SONATYPE_USERNAME ;
          kv/data/cicd/sonatype password | SONATYPE_PASSWORD ;
          kv/data/cicd/gpg secring | GPG_SECRING ;
          kv/data/cicd/gpg passphrase | GPG_PASSPHRASE ;
          kv/data/cicd/github api_token | GITHUB_API_TOKEN ;
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'liberica'
        cache: maven
        gpg-private-key: ${{ steps.secrets.outputs.GPG_SECRING }}
        gpg-passphrase: ${{ steps.secrets.outputs.GPG_PASSPHRASE }}
    - name: Unit Tests
      run: ./mvnw -V --no-transfer-progress clean compile spring-boot:process-aot test
    - name: Native Build
      if: github.ref == 'refs/heads/main'
      run: |
        set -e
        ./mvnw -V --no-transfer-progress -Pnative clean spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=ghcr.io/making/kpack-exporter
    - name: Docker Push
      if: github.ref == 'refs/heads/main'
      run: |
        set -e
        mkdir -p ~/.docker
        cat <<EOF > ~/.docker/config.json
        {"auths":{"ghcr.io":{"username":"making","password":"${GITHUB_API_TOKEN}"}}}
        EOF
        docker push ghcr.io/making/kpack-exporter
    - name: Revoke token
      if: always()
      run: |
        curl -X POST -s -H "X-Vault-Token: ${VAULT_TOKEN}" ${{ secrets.VAULT_ADDR }}/v1/auth/token/revoke-self